name: CI
on:
  push:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc # v3.6.0
        with:
          distribution: corretto
          java-version: 8
          cache: sbt

      - name: build and test
        run: sbt clean assembly

      - uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      - uses: guardian/actions-riff-raff@f2b0e163878122f6862f272f00cb51c36df3fe4b # v2.2.0
        with:
          app: crossword-status-checker
          configPath: riff-raff.yaml
          contentDirectories: |
            crossword-status-checker:
              - target/scala-2.13/crossword-status-checker.jar
