name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian
      JAVA_VERSION: 8
      SKIP_NODE: true
      NODE_PACKAGE_JSON_FILES_MISSING_LOCK: public/package.json
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
